language: java
sudo: false

deploy:
  provider: releases
  api_key:
    secure: gDQrnDKRyDhYJPY0ZHGyohpya2Q/s2HMgKRBI7zCGKfLUvowtw/+GVpPsxeC5WkppmKBHxmHveCLhrkKqrI01TrgWibMOuuRm9E+t6NwxCJdrX2teS5ypfsadvLKClWCkFHJKRHKrWvw58ohTeroqzdc8ImWyegapsEfvUa1gUTem7uIKJdQNFIikv0JGDrEUiLHTIcaUww4r1heLx/dDst7wT+Ra8iNuLJIsEt4/jhb6IxIhdprG8tAGEg7suUvVTS4lyWqr853LFkju/7LpNHVndUo25J1lzlgNRok+P1J8uBnbhf1IQ9anQnozqYvwaT/tZQcd8TxtzGPeXtVA821SE2L4GCfTqC6RZc5TIV1u/YFwaVap6xviNDHTplTatzSVxywU/du4knmfI641MXZAt+L4I3hJXFo4al1P4Fi5W3Xss9IC9ETWSTBzvvam95kg4NlM+dvhyAzOO3hWM+/gG5L3sib3LT4FG6yJwKEM2n4vusmWumXM1giCE+8a2SooPdrhOk2j2vikgJ3U8OhC3g0e1QzZGaPI45Y3qicag0GG+d8ebdb6ecRGcd6N5MKFv9IxD33LHMRb6H7hIXM1DKpX3UOYnAy//7DV0RFFZ5rK1vhwww8kwdmxryF/yMejXYIMgUdFfXK9ltliI2znSOlCuGV4+rPuLADtyU=
  file: target/release/chat.neerc.jar
  on:
    repo: Shemplo/Neerc-chat-client

script:
  - mvn clean package cobertura:cobertura

after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Build was failed"